#ifndef __ZENUM_H__
#define __ZENUM_H__

#include <cstddef>

namespace zeno {
    enum NodeType
    {
        Node_Normal,
        SubInput,
        SubOutput,
        Node_Group,
        Node_Legacy,
        Node_SubgraphNode,
        Node_Solver,
        Node_AssetInstance,     //the asset node which generated by main graph tree.
        Node_AssetReference,    //the asset node which created in another asset graph.
        NoVersionNode
    };

    enum ParamControl
    {
        NullControl,
        Lineedit,
        Multiline,
        ReadPathEdit,
        WritePathEdit,
        DirectoryPathEdit,
        Combobox,
        Checkbox,
        Vec2edit,
        Vec3edit,
        Vec4edit,
        ColorVec,
        Heatmap,
        CurveEditor,
        SpinBox,
        Slider,
        DoubleSpinBox,
        SpinBoxSlider,
        PythonEditor,
        PushButton,
        Seperator,
        CodeEditor,
        NoMultiSockPanel,   //disable dist/list panel
    };
}

enum NodeType2
{
    Node_Normal2
};


constexpr size_t _gParamType_IObject = 3738735455978425345;
constexpr size_t _gParamType_Geometry = 15350417249981042258;
constexpr size_t _gParamType_List = 13532050696470356290;
constexpr size_t _gParamType_Dict = 15211486920298196394;
constexpr size_t _gParamType_VDBGrid = 234;
constexpr size_t _gParamType_Bool = 15698046148323980066ULL;
constexpr size_t _gParamType_Int = 3143511548502526014ULL;
constexpr size_t _gParamType_Float = 11532138274943533413ULL;
constexpr size_t _gParamType_Double = 11567507311810436776ULL;
constexpr size_t _gParamType_String = 1350625706064273086ULL;
constexpr size_t _gParamType_Vec2i = 16965886646643039397ULL;
constexpr size_t _gParamType_Vec2f = 6471145251105555636ULL;
constexpr size_t _gParamType_Vec3i = 8367839167412710198ULL;
constexpr size_t _gParamType_Vec3f = 1291108797552895579ULL;
constexpr size_t _gParamType_Vec4i = 724601356907542639ULL;
constexpr size_t _gParamType_Vec4f = 5986645728587245802ULL;
constexpr size_t _gParamType_Shader = 5880748608921663691ULL;


typedef enum ZValueType {
    ZVAL_NULL = 0,
    ZVAL_INT,
    ZVAL_FLOAT,
    ZVAL_STRING,
    ZVAL_INT_ARRAY,
    ZVAL_FLOAT_ARRAY,
    ZVAL_STRING_ARRAY
} ZValueType;

enum ParamControl2
{
    ctrl_NullControl,
    ctrl_Lineedit,
    ctrl_Multiline,
    ctrl_ReadPathEdit,
    ctrl_WritePathEdit,
    ctrl_DirectoryPathEdit,
    ctrl_Combobox,
    ctrl_Checkbox,
    ctrl_Vec2edit,
    ctrl_Vec3edit,
    ctrl_Vec4edit,
    ctrl_ColorVec,
    ctrl_Heatmap,
    ctrl_CurveEditor,
    ctrl_SpinBox,
    ctrl_Slider,
    ctrl_DoubleSpinBox,
    ctrl_SpinBoxSlider,
    ctrl_PythonEditor,
    ctrl_PushButton,
    ctrl_Seperator,
    ctrl_CodeEditor,
    ctrl_NoMultiSockPanel,   //disable dist/list panel
};

struct ZValue {
    ZValueType _type;
    union {
        int i;
        float f;
        const char* s;

        struct {
            const int* data;
            size_t size;
        } iarr;

        struct {
            const float* data;
            size_t size;
        } farr;

        struct {
            const char** data;
            size_t size;
        } sarr;
    };
};

inline ZValue ZFloatArray(const float* data, size_t n) {
    ZValue z{};
    z._type = ZVAL_FLOAT_ARRAY;
    z.farr.data = data;
    z.farr.size = n;
    return z;
}

inline ZValue ZString(const char* s) {
    ZValue v{};
    v._type = ZVAL_STRING;
    v.s = s;
    return v;
}

inline ZValue ZFloat(float fval) {
    ZValue v{};
    v._type = ZVAL_FLOAT;
    v.f = fval;
    return v;
}

inline ZValue ZInt(int ival) {
    ZValue v{};
    v._type = ZVAL_INT;
    v.i = ival;
    return v;
}

inline ZValue ZNull() {
    ZValue z{};
    z._type = ZVAL_NULL;
    return z;
}

struct ZParamDescriptor {
    const char* name;   //不需要考虑内存对齐，放这里更方便
    size_t type;
    ZValue defl;
    ParamControl2 control;
    ZValue ctrl_props;
};

#endif